### ISSUE TITLE
Unknown error occured

### ISSUE THREAD

**Issue by satvikknischal** [EnzoD86/tuya-smart-ir-ac#13]
I am extremely new to HA, Github and Smarthome in general, I have a smart IR Remote that works with smartlife, couldn't figure out how to make until I found this, was installing this integration but ended up with an error. I have attached a screenshot of the error. Any help would be greatly appreciated. Thankyou

<img width="531" alt="Screenshot 2024-08-22 at 1 00 47 AM" src="https://github.com/user-attachments/assets/73318867-341f-4631-936d-a52c07eec0ee">
d-9006-44e8bd4265f9)

**Comment by EnzoD86** [comment]
Hi, can you attach the home assistant logs to understand the type of error? Thanks

**Comment by satvikknischal** [comment]
THANKS FOR THE SWIFT REPLY, HERE YOU GO!
<img width="1442" alt="Screenshot 2024-08-22 at 1 19 03 AM" src="https://github.com/user-attachments/assets/0502e9d7-f1df-4d54-a568-08e48fe175ca">

**Comment by EnzoD86** [comment]
in the project settings (on the Tuya Developer platform site), in the "service api" tab you need to enable the "IR control hub open service" api.
try following this discussion: https://github.com/EnzoD86/tuya-smart-ir-ac/issues/10

**Comment by satvikknischal** [comment]
Thankyou so much, that worked flawlessly! 
Also is there a way to make this work locally?

**Comment by EnzoD86** [comment]
At the moment this integration only works via the Tuya Cloud.
I'm trying to experiment with sending commands locally, but with poor results. I don't think it will be possible.
Furthermore, since the air conditioners are virtual entities, local operation would not be synchronized with the smart life app.

**Comment by satvikknischal** [comment]
That is sad, I don't really care for the smartlife app, but not having local control is a major turnoff for these tuya remotes. I guess I am gonna have to switch over to broadlink ones ultimately. Well anyways, thankyou so much for this integration and for helping me out truly appreciate it!
