### ISSUE TITLE
Integration don't work

### ISSUE THREAD

**Issue by PakyITA** [EnzoD86/tuya-smart-ir-ac#15]
Hello i have read a documentation and set my config.yaml but don't work.
the log is:
Registratore: homeassistant.setup
Fonte: setup.py:497
Prima occorrenza: 11:40:16 (1 occorrenze)
Ultima registrazione: 11:40:16

Unable to prepare setup for platform 'tuya_smart_ir_ac.climate': Unable to set up component.

**Comment by EnzoD86** [comment]
Fixed by extending the trial period of IoT Core APIs.
I need to update the documentation.
