### ISSUE TITLE
Unknown error occured with ZigBee IR ZS06ZS3L

### ISSUE THREAD

**Issue by teohghost** [EnzoD86/tuya-smart-ir-ac#19]
Hi I am new to this repo, I have a Zigbee IR model : ZS06ZS3L
after preset with correct IR ID and Aircond ID, I keeps seeing "Unknown Error occured", how the debug can be used?
![image](https://github.com/user-attachments/assets/6ed3edd9-4954-4f3b-9512-3326efcfbc35)

**Comment by EnzoD86** [comment]
Hi, what do you see in the logs?

**Comment by EnzoD86** [comment]
You can enable debug logs like this:

```
logger:
  logs:
    custom_components.tuya_smart_ir_ac: debug
```

**Comment by teohghost** [comment]
Hi @EnzoD86 

I have added debug into configuration.yaml and restarted full home assistant

![image](https://github.com/user-attachments/assets/a4ca4964-5843-4bb1-94d3-9d2f6d3e8517)

Then I try adding AC again
<img width="271" alt="image" src="https://github.com/user-attachments/assets/c65d8421-182d-4cd3-bc62-7e5b5c557f1f">

Then the logs
![image](https://github.com/user-attachments/assets/e0e3332c-4908-407b-97d1-c73abf4301f9)

**Comment by teohghost** [comment]
my project do have Smart Home Basic Service, is there anything else I should check? 
<img width="899" alt="image" src="https://github.com/user-attachments/assets/9167a856-3b10-4f0b-92e3-629e6713e13d">

**Comment by teohghost** [comment]
after added IR Control Hub Open Service, it works!!
