### ISSUE TITLE
A thankful note

### ISSUE THREAD

**Issue by bdteo** [EnzoD86/tuya-smart-ir-ac#22]
Thank you very much. It works like a charm! 
It happens changing HVAC modes is something that is not working but I saw in the error logs it is some API problem and it might be on Tuya's behalf, so it is okay.
Anyway, wonderful job!

**Comment by EnzoD86** [comment]
Thanks! can you post the error logs so I can investigate?

**Comment by bdteo** [comment]
Here's the anonymized error log:

```
homeassistant  | 2024-09-08 10:36:13.197 ERROR (MainThread) [custom_components.tuya_smart_ir_ac] Error sending multiple command to climate <DEVICE_ID_1>: {'url': '/v2.0/infrareds/<DEVICE_ID_2>/air-conditioners/<DEVICE_ID_1>/scenes/command', 'request': {'power': '1', 'mode': '1', 'temp': '22.0', 'wind': '0'}, 'response': {'code': 30100, 'msg': '没有查询到码库', 'success': False, 't': <TIMESTAMP_1>, 'tid': '<TRANSACTION_ID_1>'}}
homeassistant  | 2024-09-08 10:36:13.197 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [<CONNECTION_ID>] Unable to change hvac mode
homeassistant  | 2024-09-08 10:36:19.836 ERROR (MainThread) [custom_components.tuya_smart_ir_ac] Error sending multiple command to climate <DEVICE_ID_1>: {'url': '/v2.0/infrareds/<DEVICE_ID_2>/air-conditioners/<DEVICE_ID_1>/scenes/command', 'request': {'power': '1', 'mode': '4', 'temp': '22.0', 'wind': '0'}, 'response': {'code': 30100, 'msg': '没有查询到码库', 'success': False, 't': <TIMESTAMP_2>, 'tid': '<TRANSACTION_ID_2>'}}
homeassistant  | 2024-09-08 10:36:19.836 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [<CONNECTION_ID>] Unable to change hvac mode
homeassistant  | 2024-09-08 10:36:22.936 ERROR (MainThread) [custom_components.tuya_smart_ir_ac] Error sending multiple command to climate <DEVICE_ID_1>: {'url': '/v2.0/infrareds/<DEVICE_ID_2>/air-conditioners/<DEVICE_ID_1>/scenes/command', 'request': {'power': '1', 'mode': '3', 'temp': '22.0', 'wind': '0'}, 'response': {'code': 30100, 'msg': '没有查询到码库', 'success': False, 't': <TIMESTAMP_3>, 'tid': '<TRANSACTION_ID_3>'}}
homeassistant  | 2024-09-08 10:36:22.936 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [<CONNECTION_ID>] Unable to change hvac mode
```

### Error Analysis

The logs show multiple failed attempts to send commands to a Tuya Smart IR AC device. The key points are:

1. The error occurs in the `custom_components.tuya_smart_ir_ac` component.
2. It's trying to send commands to change the HVAC mode.
3. The response from the Tuya API consistently returns an error code 30100.
4. The error message in Chinese ("没有查询到码库") translates to "No code library found" or "Failed to query the code library".

**Comment by EnzoD86** [comment]
Strange, this type of error had not yet been reported to me.
From the smart life or tuya application, can you change the mode?
If you can change the mode from the application, is there any parameter that is moved to a default value (temperature, hvac mode or fan speed)?

**Comment by bdteo** [comment]
@EnzoD86 Thank you very much for the feedback, bro! 
Well, I can in fact change it from the Smart Life application.

The funny thing is there is probably some internal knowledge that Tuya (or Google) do not share because (no matter how mangled the UI of the device in Google Home) I am quite able to control its Heat/Auto/Cooling modes using my voice assistant.

_Just a little note of frustration: After spending like 10s of hours on the problem I am quite disappointed with both Tuya and Google in regards to smart home applications. These guys are a joke when it comes to software support._

I can probably try to do some Android VM install with some self signed certificates on the certificate chain and try to intercept the HTTP requests from the Smart Life app (accepting any legal liability myself) but this might be a lot of work.

If you are aware of any easier way or a resource that is an easier route of action, please let me know.

PS. I think it might have something to do with differences in the way these requests should be constructed for different models of ACs and the one I am trying to control is a pretty popular and generic AUX 24 BTUs one

**Comment by bdteo** [comment]
> Strange, this type of error had not yet been reported to me. From the smart life or tuya application, can you change the mode? If you can change the mode from the application, is there any parameter that is moved to a default value (temperature, hvac mode or fan speed)?

Well, might later these days check it in my HA install. This is really a good idea. Thank you!

**Comment by EnzoD86** [comment]
> I can probably try to do some Android VM install with some self signed certificates on the certificate chain and try to intercept the HTTP requests from the Smart Life app (accepting any legal liability myself) but this might be a lot of work.

No, you don't need to waste all this time!
Tuya has tried to standardize the API for all air conditioners; probably when changing the HVAC mode the integration is trying to send an unsupported command.
For example, when sending the command to change the HVAC mode, it may not like the fan being switched back to AUTO mode.
This problem happened to me with some models only for DRY mode.
This can be understood from Smartlife; when you change the HVAC mode, what value does the fan speed set to?

**Comment by bdteo** [comment]
Thank you @EnzoD86!

Well, I conducted the test you mentioned. As it happens fan speed is not changed. However, I did observe that any time I change the HVAC mode the temperature goes to exactly 25 degrees Celsius 😅. Quite a fun stuff!

Could this be the reason?

If yes, then can I please kindly ask you to add an input field in the initial configuration dialogue for a baseline temperature setting?

What do you think? I will be quite glad to learn your input. 

Thank you very much for the support again!

**Comment by EnzoD86** [comment]
Yes, the temperature is most likely responsible!
I don't understand the motivation behind Tuya's choice.
Before making any changes to the integration, I ask you for another test.
If you set the temperature to 25 degrees and try to change the hvac mode from the integration, does it work?
Thank you

**Comment by EnzoD86** [comment]
> Yes, the temperature is most likely responsible! I don't understand the motivation behind Tuya's choice. Before making any changes to the integration, I ask you for another test. If you set the temperature to 25 degrees and try to change the hvac mode from the integration, does it work? Thank you

I forgot.. also in dry mode set the temperature to 25 from SmartLife?
Thank you

**Comment by EnzoD86** [comment]
hi @bdteo, 
I'm waiting for your news! 
Thanks
