### ISSUE TITLE
Issue happened after following sections in your configuration.yaml and restart HA

### ISSUE THREAD

**Issue by Xuantam91** [EnzoD86/tuya-smart-ir-ac#24]
logger: homeassistant.setupSource: setup.py:269First occurred: 22:17:36 (1 occurrences)Last logged: 22:17:36Setup failed for custom integration 'tuya_smart_ir_ac': Integration failed to initialize.

This error originated from a custom integration.

Logger: custom_components.tuya_smart_ir_ac
Source: custom_components/tuya_smart_ir_ac/__init__.py:49
integration: Tuya Smart IR AC (documentation, issues)
First occurred: 22:17:36 (1 occurrences)
Last logged: 22:17:36

Tuya Open API login error

**Comment by Xuantam91** [comment]
I creat new develop cloud app then config, it works.
But small issue is how can I change temperature to C?
Currently it is F, entity from My IR Hub is C
<img width="420" alt="Screenshot 2024-09-23 at 22 57 50" src="https://github.com/user-attachments/assets/2b7ac8df-3658-4d57-b16f-4a36b5270177">

**Comment by EnzoD86** [comment]
Hi, the integration only works using Celsius..
Have you tried to look in the Home Assistant settings? Settings -> System -> General
You should be able to set the type of Unit of measurement.
Let me know!

**Comment by Xuantam91** [comment]
Great, my setup in system is F..
Just change it.. thanks 😊

**Comment by Xuantam91** [comment]
One more, any chance to get changes to Home assistant if I change mode or temperature by air conditioner remote?

**Comment by EnzoD86** [comment]
> One more, any chance to get changes to Home assistant if I change mode or temperature by air conditioner remote?


Something like this could be done using esp home, building a receiver and transmitter to be placed near the split, able to receive signals both from the remote control (updating the Home assistant status) and via wifi to then send them to the air conditioner. But it would be something that is outside the scope of this integration.

**Comment by Xuantam91** [comment]
Understood, thank for your support!
