### ISSUE TITLE
The current temperature is not updated

### ISSUE THREAD

**Issue by driagi** [EnzoD86/tuya-smart-ir-ac#25]
The current temperature is not updated. Just by giving commands, the temperature updates

**Comment by EnzoD86** [comment]
Hi, thanks for reporting.
I confirm the bug is there.
I will release the fix in the next few days!

**Comment by EnzoD86** [comment]
Fixed

**Comment by driagi** [comment]
Continue to have misaligned temperatures.
![image](https://github.com/user-attachments/assets/64c041a3-b051-4dde-9aa2-2ba11884f6df)
