### ISSUE TITLE
Issue with Air Flap Direction

### ISSUE THREAD

**Issue by Tinux-Git** [EnzoD86/tuya-smart-ir-ac#31]
Hi everyone, I use the integration with pleasure but I am having a problem with the direction of the air flaps. Basically, when I start the air conditioner, the flaps automatically position themselves "shooting" air downwards. Do you know if there is a way to control the direction of the air flaps?

**Comment by EnzoD86** [comment]
Hi, unfortunately the Tuya API does not support the ability to change the vertical and horizontal swing.
I do not know if they will implement it in the future.

**Comment by Tinux-Git** [comment]
thanks for the support... what I don't understand is why you set them by default in that way

**Comment by EnzoD86** [comment]
The integration does not set them, because it is not able to do so.
When you turn on the air conditioner from smart life how does it behave?

**Comment by Tinux-Git** [comment]
I have 4 air conditioners with 4 IR devices and only one works this way

**Comment by EnzoD86** [comment]
but if you set them in a certain way from its remote control, does it still reset when you turn it on?

**Comment by Tinux-Git** [comment]
yes

**Comment by EnzoD86** [comment]
it's strange...
but I didn't understand if the problem also occurs directly when you use smart life.

The only air conditioner that has this behavior, is it a different model than the others?

**Comment by Tinux-Git** [comment]
all the same

**Comment by EnzoD86** [comment]
have you tried moving/invert the IR HUBs and see if it has the same behavior?

**Comment by Tinux-Git** [comment]
yes exactly the same

**Comment by EnzoD86** [comment]
I still don't know if there is some default setting on that air conditioner that you have that problem with... I have no more ideas.. :(
