### ISSUE TITLE
Unable to add device

### ISSUE THREAD

**Issue by vdlaptrinh** [EnzoD86/tuya-smart-ir-ac#32]
I have a Tuya Smart IR S09 device like the picture: it displays temperature, humidity and date. I also installed tuya_smart_ir_ac. I also added Tuya Access ID, Tuya Access Secret to configuration.yaml.
I have entered the full: infrared hub ID, Air conditioner ID, Air conditioner name. But Could not connect to device; check the log for more information.
Please help me.
Thanks
![CaptureTuya](https://github.com/user-attachments/assets/a2f67703-6c95-45e2-bec3-dd0a392a58fa)
![smart ir](https://github.com/user-attachments/assets/4cfd8afc-c0fc-4072-86e3-292be3f6c915)

**Comment by EnzoD86** [comment]
Hi, I confirm that this device is supported because I use it too, probably you just need to activate some API on the Tuya platform.
Can you see what error is logged in home assistant logs?

**Comment by vdlaptrinh** [comment]
2024-11-17 10:48:51.959 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration tuya_smart_ir_ac which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant

**Comment by vdlaptrinh** [comment]
![tuya2](https://github.com/user-attachments/assets/2faf38d5-5358-4bd7-92f9-6f8aecb4b142)

**Comment by vdlaptrinh** [comment]
I have added it. Thank you very much.
- I add API: IR Control Hub Open Service. 
- I changed country: "EU" to country: "US"
- 
![TUYA21](https://github.com/user-attachments/assets/79ef55c7-4ade-40ba-92e1-4102779ad0b1)

**Comment by EnzoD86** [comment]
perfect, I'm glad you solved it!
