### ISSUE TITLE
Error fetching all data for climates

### ISSUE THREAD

**Issue by frentemorao** [EnzoD86/tuya-smart-ir-ac#33]
Hi Enzo

As I mentioned your integration worked flawlessly for me.
I have just realized that I can no longer use it because my IR's controller appears to be unavailable.

Here you can see what I have found in the logs:

`Este error se originó a partir de una integración personalizada.

Registrador: custom_components.tuya_smart_ir_ac
Fuente: custom_components/tuya_smart_ir_ac/api.py:21
integración: Tuya Smart IR AC (documentación, problemas)
Ocurrió por primera vez: 17:04:42 (2 ocurrencias)
Última vez registrado: 17:05:57

Error fetching all data for climates {'bfc1926497a2b14a05h4jm', 'bfb32343c5c1d5db3auzsv'}: {'url': '/v1.0/cloud/rc/infrared/ac/status/batch?device_ids=bfc1926497a2b14a05h4jm,bfb32343c5c1d5db3auzsv', 'request': '', 'response': {'code': 40001900, 'msg': 'No space permission', 'success': False, 't': 1732464282516, 'tid': 'd0f044deaa7d11ef9520ae18e4d9fbe2'}}
Error fetching all data for climates {'bfc1926497a2b14a05h4jm', 'bfb32343c5c1d5db3auzsv'}: {'url': '/v1.0/cloud/rc/infrared/ac/status/batch?device_ids=bfc1926497a2b14a05h4jm,bfb32343c5c1d5db3auzsv', 'request': '', 'response': {'code': 40001900, 'msg': 'No space permission', 'success': False, 't': 1732464356325, 'tid': 'fced6baeaa7d11ef9e6566852e0618f4'}}`

I confirm you I have all the mandatory services "in service"
![imagen](https://github.com/user-attachments/assets/bea6b656-3cef-41e4-bc9e-0c506bd72993)

**Comment by EnzoD86** [comment]
hi, can you show me the detail under the "Iot core" api by clicking on it?

**Comment by frentemorao** [comment]
yes for sure
![imagen](https://github.com/user-attachments/assets/6cf96658-b51e-48f1-b40c-e723c8c96c98)

**Comment by EnzoD86** [comment]
I see you have requested an extension; how long ago was it?

**Comment by frentemorao** [comment]
It was about 2 months ago because I saw a comment of yours in another thread.
It worked perfectly for 1,5 months until it got broken

**Comment by EnzoD86** [comment]
I ask you another screenshot... if you click next to IotCore (on the plus) can you show me what is shown?

Even though I know I'm asking you obvious questions, I have to ask them...
Are these the tuya api connected to the project configured in your Home Assistant configuration.yaml?
Does the region configured in home assistant correspond to the region of the project on the tuya platform?

**Comment by frentemorao** [comment]
Hi Enzo

I think I have figured out the problem.
Last week I removed a Smart IR AC in the Tuya app BUT I forgot to remove the device/entities in Home Assistant...
I have just removed them from HA and now it is working flawlessly as always (after a restart, of course)

By the way, do you know what will happen in 2025-04-11 when the extension period will expire??

![imagen](https://github.com/user-attachments/assets/c29d410b-1477-4927-a174-c13abbf90b9a)

**Comment by EnzoD86** [comment]
Perfect!
So the integration was trying to download information from a device that is no longer registered.
From the error message it would have been impossible to understand the problem.

As for the expiration of the api, I am not sure what could happen... probably nothing...

my current situation is as follows:
![image](https://github.com/user-attachments/assets/fe44567e-a25e-485b-b069-6814a45f1868)
and I can assure you that the integration works perfectly!

At worst, you will probably have to request a further extension!
See you soon bye!
